### ISSUE TITLE
Contributed to upstream?

### ISSUE THREAD

**Issue by MrBollie** [onkelDead/tascam-driver-patch#1]
Hey there!

Very nice work there! I also tried making my own mixer GUI, but it never became as sophisticated as your project here.

Have you submitted your patch to the kernel developers already? Would be so great to see this coming with mainline kernels.

Cheers
Bollie

**Comment by trebmuh** [comment]
Adding my voice here.
Upstreaming it (whether it's relevant for the kernel people, or the alsa ones) would be a brilliant step forward.

**Comment by onkelDead** [comment]
It's on the way, thanks for your motivations.

I've had to change a lot of things to get my code in the correct style.
So I'll put the last updated patch here and will upgrade the repo tascamgtk asap.
I'll keep you informed about further process.

Greets
Detlef
