### ISSUE TITLE
patching 

### ISSUE THREAD

**Issue by disasterman573** [onkelDead/tascam-driver-patch#3]
Thanks for you contributions to this project.  I am attempting to patch and get the following:

make prepare
make[1]: *** No rule to make target 'arch/x86/entry/syscalls/syscall_32.tbl', needed by 'arch/x86/entry/syscalls/../../include/generated/asm/syscalls_32.h'.  Stop.
arch/x86/Makefile:245: recipe for target 'archheaders' failed
make: *** [archheaders] Error 2

Any help would be appreciated

**Comment by onkelDead** [comment]
Hi,

sorry, but I guess your issue isn't a result of this patch.
"make prepare" must be run before you apply the patch file into kernel sources.

I hope you'll find more help elsewhere.

greets
Detlef
